import { Aroma } from './types';

export const AROMAS_LIST: Aroma[] = [
  {
    id: 'lavanda',
    name: 'Lavanda',
    category: 'Serenidade e Repouso',
    benefits: 'Acalma mentes agitadas, induz ao sono tranquilo e dissipa a ansiedade e o pânico.',
    notes: 'Floral, Doce, Suave',
    intensity: 65,
    tags: ['Calma', 'Sono', 'Paz', 'Alívio', 'Perdão', 'Serenidade'],
    imageUrl: '/images/aromas/lavanda.jpg'
  },
  {
    id: 'camomila',
    name: 'Camomila',
    category: 'Acalento e Suavidade',
    benefits: 'Alivia ansiedade, tensão emocional, aflição e sentimentos de abandono.',
    notes: 'Doce, Herbáceo, Frutado',
    intensity: 55,
    tags: ['Ansiedade', 'Relaxamento', 'Compaixão', 'Aflição'],
    imageUrl: '/images/aromas/camomila.jpg'
  },
  {
    id: 'hortela',
    name: 'Hortelã',
    category: 'Foco e Despertar',
    benefits: 'Combate cansaço físico e mental, acalma inquietação e estimula a concentração lúcida.',
    notes: 'Mentolado Fresco, Vigoroso',
    intensity: 85,
    tags: ['Cansaço', 'Concentração', 'Agitação', 'Inquietação'],
    imageUrl: '/images/aromas/hortela.jpg'
  },
  {
    id: 'baunilha',
    name: 'Baunilha',
    category: 'Conforto e Doçura',
    benefits: 'Acolhe a tristeza profunda, decepções e carência, trazendo calor e sensação de pertencimento.',
    notes: 'Doce, Quente, Envolvente',
    intensity: 80,
    tags: ['Tristeza', 'Conforto', 'Acolhimento', 'Pertencimento', 'Carência'],
    imageUrl: '/images/aromas/baunilha.jpg'
  },
  {
    id: 'sandalo',
    name: 'Sândalo',
    category: 'Paz Interior e Equilíbrio',
    benefits: 'Dissipa raiva, angústia e mágoas, restaurando a paciência, harmonia e aceitação.',
    notes: 'Amadeirado Nobre, Terroso',
    intensity: 75,
    tags: ['Raiva', 'Paciência', 'Harmonia', 'Aceitação', 'Angústia'],
    imageUrl: '/images/aromas/sandalo.jpg'
  },
  {
    id: 'cedro',
    name: 'Cedro',
    category: 'Segurança e Estrutura',
    benefits: 'Enraíza a autoconfiança, combate medo e insegurança, promovendo perseverança firme.',
    notes: 'Amadeirado Seco, Resinoso',
    intensity: 70,
    tags: ['Medo', 'Insegurança', 'Segurança', 'Autoconfiança', 'Perseverança'],
    imageUrl: '/images/aromas/cedro.jpg'
  },
  {
    id: 'rosa',
    name: 'Rosa',
    category: 'Amor e Sensibilidade',
    benefits: 'Acolhe o coração partido, dissipa timidez e vergonha, despertando amor, afeto e generosidade.',
    notes: 'Floral Nobre, Delicado, Aveludado',
    intensity: 90,
    tags: ['Amor', 'Romance', 'Generosidade', 'Encanto', 'Altruísmo'],
    imageUrl: '/images/aromas/rosa.jpg'
  },
  {
    id: 'laranja',
    name: 'Laranja',
    category: 'Alegria e Luminosidade',
    benefits: 'Irradia felicidade espontânea, vitalidade, amizade acolhedora e solidariedade.',
    notes: 'Cítrico Solar, Doce, Fresco',
    intensity: 75,
    tags: ['Felicidade', 'Vitalidade', 'Amizade', 'Solidariedade'],
    imageUrl: '/images/aromas/laranja.jpg'
  },
  {
    id: 'bergamota',
    name: 'Bergamota',
    category: 'Leveza e Renascimento',
    benefits: 'Dissipa o desânimo e a apatia, restaurando a leveza interior e a confiança alegre.',
    notes: 'Cítrico Fino, Toque Floral',
    intensity: 75,
    tags: ['Desânimo', 'Leveza', 'Apatia', 'Confiança'],
    imageUrl: '/images/aromas/bergamota.jpg'
  },
  {
    id: 'alecrim',
    name: 'Alecrim',
    category: 'Clareza e Motivação',
    benefits: 'Desperta a mente, elimina confusão e dispersão, impulsionando foco e motivação ativa.',
    notes: 'Herbáceo Fresco, Estimulante',
    intensity: 80,
    tags: ['Foco', 'Motivação', 'Clareza', 'Confusão'],
    imageUrl: '/images/aromas/alecrim.jpg'
  },
  {
    id: 'limao',
    name: 'Limão',
    category: 'Energia e Purificação',
    benefits: 'Desperta a energia vital, combate tédio e descontentamento, convidando à renovação e recomeço.',
    notes: 'Cítrico Puro, Vibrante, Refrescante',
    intensity: 85,
    tags: ['Energia', 'Renovação', 'Recomeço', 'Descontentamento'],
    imageUrl: '/images/aromas/limao.jpg'
  },
  {
    id: 'ylangylang',
    name: 'Ylang-ylang',
    category: 'Sensualidade e Desaceleração',
    benefits: 'Alivia estresse e tensão nervosa, despertando fascinação, paixão e entrega aos sentidos.',
    notes: 'Floral Exótico, Doce, Marcante',
    intensity: 90,
    tags: ['Estresse', 'Paixão', 'Fascinação', 'Desejo'],
    imageUrl: '/images/aromas/ylangylang.jpg'
  },
  {
    id: 'jasmim',
    name: 'Jasmim',
    category: 'Acolhimento e Fascínio',
    benefits: 'Preenche a solidão e sensação de rejeição com profunda admiração, encantamento e intimidade calorosa.',
    notes: 'Floral Nobre, Exótico, Noturno',
    intensity: 95,
    tags: ['Solidão', 'Encantamento', 'Rejeição', 'Intimidade', 'Fascínio'],
    imageUrl: '/images/aromas/jasmim.jpg'
  },
  {
    id: 'eucalipto',
    name: 'Eucalipto',
    category: 'Expansão e Libertação',
    benefits: 'Dissipa frustração, irritação e tensão acumulada, abrindo espaço para frescor mental e respiração ampla.',
    notes: 'Cânforaceo, Refrescante, Penetrante',
    intensity: 85,
    tags: ['Frustração', 'Irritação', 'Frescor', 'Tensão', 'Alarme'],
    imageUrl: '/images/aromas/eucalipto.jpg'
  },
  {
    id: 'canela',
    name: 'Canela',
    category: 'Calor e Afeto',
    benefits: 'Aquece a saudade e a nostalgia, dissipa ciúmes e arrependimento com calor estimulante.',
    notes: 'Especiado Quente, Intenso',
    intensity: 95,
    tags: ['Saudade', 'Nostalgia', 'Desejo', 'Calor'],
    imageUrl: '/images/aromas/canela.jpg'
  },
  {
    id: 'verbena',
    name: 'Verbena',
    category: 'Inspiração e Fluidez',
    benefits: 'Acende a criatividade, curiosidade intelectual e inspiração artística e mental.',
    notes: 'Cítrico Herbáceo, Nobre, Fresco',
    intensity: 75,
    tags: ['Criatividade', 'Curiosidade', 'Inspiração'],
    imageUrl: '/images/aromas/verbena.jpg'
  },
  {
    id: 'flor_de_laranjeira',
    name: 'Flor de laranjeira',
    category: 'Esperança e Encanto',
    benefits: 'Desperta esperança luminosa, profunda gratidão e ampara a vulnerabilidade emocional.',
    notes: 'Floral Suave, Cítrico Delicado',
    intensity: 75,
    tags: ['Esperança', 'Gratidão', 'Vulnerabilidade', 'Encantamento'],
    imageUrl: '/images/aromas/flor_de_laranjeira.jpg'
  },
  {
    id: 'patchouli',
    name: 'Patchouli',
    category: 'Presença e Firmeza',
    benefits: 'Fortalece a confiança e o ancoramento, dissolvendo ressentimentos e medos interiores.',
    notes: 'Terroso Intenso, Amadeirado, Úmido',
    intensity: 85,
    tags: ['Confiança', 'Ressentimento', 'Presença'],
    imageUrl: '/images/aromas/patchouli.jpg'
  },
  {
    id: 'gengibre',
    name: 'Gengibre',
    category: 'Coragem e Impulso',
    benefits: 'Desperta coragem indômita, determinação, superação de obstáculos e espírito de aventura.',
    notes: 'Picante, Quente, Estimulante',
    intensity: 90,
    tags: ['Coragem', 'Determinação', 'Superação', 'Aventura'],
    imageUrl: '/images/aromas/gengibre.jpg'
  },
  {
    id: 'cha_verde',
    name: 'Chá verde',
    category: 'Serenidade e Harmonia',
    benefits: 'Induz à paz contemplativa, paciência reflexiva, serenidade e equilíbrio interior.',
    notes: 'Verde Puro, Herbáceo Sutil',
    intensity: 60,
    tags: ['Paz', 'Serenidade', 'Espera', 'Humildade'],
    imageUrl: '/images/aromas/cha_verde.jpg'
  },
  {
    id: 'tangerina',
    name: 'Tangerina',
    category: 'Alegria e Descontração',
    benefits: 'Desperta o riso sincero, leveza descontraída, otimismo e expectativa positiva.',
    notes: 'Cítrico Frutado, Espumante, Doce',
    intensity: 70,
    tags: ['Alegria', 'Descontração', 'Expectativa', 'Surpresa'],
    imageUrl: '/images/aromas/tangerina.jpg'
  },
  {
    id: 'capim_limao',
    name: 'Capim-limão',
    category: 'Liberdade e Descoberta',
    benefits: 'Estimula a curiosidade viva, sensação de liberdade e renovação lúcida das ideias.',
    notes: 'Cítrico Herbáceo, Limpo, Verde',
    intensity: 80,
    tags: ['Curiosidade', 'Liberdade', 'Frescor'],
    imageUrl: '/images/aromas/capim_limao.jpg'
  },
  {
    id: 'grapefruit',
    name: 'Grapefruit',
    category: 'Empolgação e Euforia',
    benefits: 'Desperta empolgação vibrante, euforia sadia, surpresa estimulante e ânimo elevado.',
    notes: 'Cítrico Amargo-Doce, Revigorante',
    intensity: 75,
    tags: ['Empolgação', 'Euforia', 'Surpresa'],
    imageUrl: '/images/aromas/grapefruit.jpg'
  },
  {
    id: 'vetiver',
    name: 'Vetiver',
    category: 'Equilíbrio e Estabilidade',
    benefits: 'Resgata estabilidade em momentos de dúvida e desespero, promovendo persistência serena.',
    notes: 'Amadeirado Úmido, Terroso Profundo, Raiz',
    intensity: 85,
    tags: ['Equilíbrio', 'Persistência', 'Dúvida', 'Estabilidade'],
    imageUrl: '/images/aromas/vetiver.jpg'
  },
  {
    id: 'iris',
    name: 'Íris',
    category: 'Introspecção e Dignidade',
    benefits: 'Acolhe a melancolia e introspecção silenciosa, restaurando nobreza interior e calma reflexiva.',
    notes: 'Floral Terroso Nobre, Atalcado',
    intensity: 70,
    tags: ['Introspecção', 'Melancolia', 'Dignidade'],
    imageUrl: '/images/aromas/iris.jpg'
  },
  {
    id: 'coco',
    name: 'Coco',
    category: 'Prazer e Acolhimento',
    benefits: 'Nutre a carência afetiva com sensação de prazer descontraído, aconchego e ternura leve.',
    notes: 'Gourmand Cremoso, Doce Suave, Tropical',
    intensity: 75,
    tags: ['Prazer', 'Carência', 'Aconchego'],
    imageUrl: '/images/aromas/coco.jpg'
  },
  {
    id: 'mirra',
    name: 'Mirra',
    category: 'Perdão e Transmutação',
    benefits: 'Auxilia na transmutação de culpas e arrependimentos profundos, abrindo espaço para autoperdão e paz.',
    notes: 'Resinoso Quente, Balsâmico, Nobre',
    intensity: 80,
    tags: ['Culpa', 'Arrependimento', 'Perdão'],
    imageUrl: '/images/aromas/mirra.jpg'
  }
];

export const OFFICIAL_SENTIMENT_TO_AROMA: Record<string, string> = {
  'Calma': 'lavanda',
  'Ansiedade': 'camomila',
  'Cansaço': 'hortela',
  'Tristeza': 'baunilha',
  'Raiva': 'sandalo',
  'Medo': 'cedro',
  'Amor': 'rosa',
  'Felicidade': 'laranja',
  'Desânimo': 'bergamota',
  'Foco': 'alecrim',
  'Energia': 'limao',
  'Estresse': 'ylangylang',
  'Solidão': 'jasmim',
  'Frustração': 'eucalipto',
  'Saudade': 'canela',
  'Criatividade': 'verbena',
  'Esperança': 'flor_de_laranjeira',
  'Confiança': 'patchouli',
  'Coragem': 'gengibre',
  'Concentração': 'hortela',
  'Relaxamento': 'camomila',
  'Sono': 'lavanda',
  'Motivação': 'alecrim',
  'Conforto': 'baunilha',
  'Romance': 'rosa',
  'Paz': 'cha_verde',
  'Alegria': 'tangerina',
  'Irritação': 'eucalipto',
  'Insegurança': 'cedro',
  'Nostalgia': 'canela',
  'Curiosidade': 'capim_limao',
  'Empolgação': 'grapefruit',
  'Paciência': 'sandalo',
  'Equilíbrio': 'vetiver',
  'Renovação': 'limao',
  'Acolhimento': 'baunilha',
  'Determinação': 'gengibre',
  'Serenidade': 'lavanda',
  'Clareza': 'alecrim',
  'Leveza': 'bergamota',
  'Vitalidade': 'laranja',
  'Introspecção': 'iris',
  'Encantamento': 'jasmim',
  'Segurança': 'cedro',
  'Gratidão': 'flor_de_laranjeira',
  'Prazer': 'coco',
  'Liberdade': 'capim_limao',
  'Harmonia': 'sandalo',
  'Frescor': 'eucalipto',
  'Descontração': 'tangerina',
  'Culpa': 'mirra',
  'Vergonha': 'rosa',
  'Inveja': 'limao',
  'Ciúme': 'canela',
  'Orgulho': 'cedro',
  'Alívio': 'lavanda',
  'Tensão': 'eucalipto',
  'Agitação': 'hortela',
  'Impaciência': 'gengibre',
  'Confusão': 'alecrim',
  'Dúvida': 'vetiver',
  'Decepção': 'baunilha',
  'Fracasso': 'sandalo',
  'Rejeição': 'jasmim',
  'Abandono': 'camomila',
  'Carência': 'baunilha',
  'Admiração': 'jasmim',
  'Encanto': 'rosa',
  'Fascinação': 'ylangylang',
  'Surpresa': 'grapefruit',
  'Perseverança': 'cedro',
  'Compaixão': 'camomila',
  'Empatia': 'lavanda',
  'Generosidade': 'rosa',
  'Amizade': 'laranja',
  'Pertencimento': 'baunilha',
  'Intimidade': 'jasmim',
  'Paixão': 'ylangylang',
  'Desejo': 'canela',
  'Espera': 'cha_verde',
  'Expectativa': 'tangerina',
  'Inquietação': 'hortela',
  'Vulnerabilidade': 'flor_de_laranjeira',
  'Melancolia': 'iris',
  'Desespero': 'vetiver',
  'Angústia': 'sandalo',
  'Pânico': 'lavanda',
  'Incerteza': 'cedro',
  'Apatia': 'bergamota',
  'Tédio': 'limao',
  'Frieza': 'eucalipto',
  'Ressentimento': 'patchouli',
  'Arrependimento': 'mirra',
  'Perdão': 'lavanda',
  'Aceitação': 'sandalo',
  'Superação': 'gengibre',
  'Recomeço': 'limao',
  'Tranquilidade': 'lavanda',
  'Euforia': 'grapefruit',
  'Apreensão': 'cedro',
  'Desconfiança': 'vetiver',
  'Timidez': 'rosa',
  'Humildade': 'cha_verde',
  'Satisfação': 'baunilha',
  'Descontentamento': 'limao',
  'Mágoa': 'sandalo',
  'Aflição': 'camomila',
  'Alarme': 'eucalipto',
  'Excitação': 'gengibre',
  'Fascínio': 'jasmim',
  'Altruísmo': 'rosa',
  'Solidariedade': 'laranja',
  'Autoconfiança': 'cedro',
  'Persistência': 'vetiver',
  'Humilhação': 'iris',
  'Inspiração': 'verbena',
  'Respeito': 'cedro',
  'Aventura': 'gengibre'
};
