import { Aroma } from './types';

export const AROMAS_LIST: Aroma[] = [
  // Calma e redução de ansiedade
  { id: 'lavanda', name: 'Lavanda', category: 'Calma e redução de ansiedade', benefits: 'Reduz ansiedade e acalma mentes agitadas.', notes: 'Floral, Doce', intensity: 60, tags: ['Calma', 'Sono', 'Paz'], imageUrl: 'https://www.medicinanatural.com.br/wp-content/uploads/lavanda-lavandula-angustifolia.jpg' },
  { id: 'camomila', name: 'Camomila', category: 'Calma e redução de ansiedade', benefits: 'Alivia irritação e tensão emocional.', notes: 'Doce, Herbáceo', intensity: 50, tags: ['Leveza', 'Relaxamento'], imageUrl: 'https://www.petz.com.br/blog/wp-content/uploads/2021/11/como-plantar-camomila-1.jpg' },
  { id: 'neroli', name: 'Neroli', category: 'Calma e redução de ansiedade', benefits: 'Auxilia em momentos de pânico e sobrecarga.', notes: 'Floral, Cítrico', intensity: 70, tags: ['Resgate', 'Equilíbrio'], imageUrl: 'https://ita.travel/user/blogimg/leto/ostatni/neroli-uvod.jpg' },
  { id: 'melissa', name: 'Melissa', category: 'Calma e redução de ansiedade', benefits: 'Acalma angústia silenciosa.', notes: 'Cítrico, Herbáceo', intensity: 45, tags: ['Acolhimento', 'Suavidade'], imageUrl: 'https://s2-globorural.glbimg.com/cvWfWZBUa-O7AvslHZ_eq0KIu1o=/0x0:780x440/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_afe5c125c3bb42f0b5ae633b58923923/internal_photos/bs/2022/2/w/LIQnJaS1CTUkfdp6xTiQ/2017-05-10-14765159963-2c70c5fab5-k.jpg' },
  { id: 'sandalo', name: 'Sândalo', category: 'Calma e redução de ansiedade', benefits: 'Aquece e reduz pensamentos excessivos.', notes: 'Amadeirado, Terroso', intensity: 75, tags: ['Meditação', 'Presença'], imageUrl: 'https://cdn.shopify.com/s/files/1/1740/9561/files/sandalo-flor_large.jpg?v=1553267580' },
  { id: 'olibano', name: 'Olíbano (Frankincense)', category: 'Calma e redução de ansiedade', benefits: 'Auxilia contra o medo e inquietação.', notes: 'Resinoso, Toque Limão', intensity: 80, tags: ['Espiritualidade', 'Proteção'], imageUrl: 'https://anba.com.br/wp-content/uploads/2022/09/B-sacra-Omam-Arabic-peninsula-scaled.jpg' },
  { id: 'manjerona', name: 'Manjerona', category: 'Calma e redução de ansiedade', benefits: 'Alivia o estresse acumulado.', notes: 'Quente, Herbáceo', intensity: 65, tags: ['Alívio', 'Descanso'], imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxkAiuWslqP1S6UiMQj9pXfzhY9tCFGRiVfGDCmtA9z5IL6wnTdhUttqqty1kPqHYnOs9c1jJaPodW0lmtwRDkGlJpFgj9rx3y5FCU3E0&s=10' },
  { id: 'cedro', name: 'Cedro', category: 'Calma e redução de ansiedade', benefits: 'Combate sensação de insegurança.', notes: 'Amadeirado, Seco', intensity: 70, tags: ['Estrutura', 'Segurança'], imageUrl: 'https://www.viveiroambiental.com.br/uploads/produtos/11052016113148.jpg' },

  // Tristeza e acolhimento emocional
  { id: 'bergamota', name: 'Bergamota', category: 'Tristeza e acolhimento emocional', benefits: 'Auxilia em tristezas leves e desânimo.', notes: 'Cítrico, Floral', intensity: 75, tags: ['Alegria', 'Confiança'], imageUrl: 'https://img.elo7.com.br/product/zoom/286D17C/economico-perf-de-ambientes-bergamota-c-flor-de-laranj-aromatizador.jpg' },
  { id: 'rosa', name: 'Rosa', category: 'Tristeza e acolhimento emocional', benefits: 'Acolhe corações partidos e luto emocional.', notes: 'Floral Intenso', intensity: 90, tags: ['Amor', 'Consolo'], imageUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBedVXEaDwLOm0bm0v2VyJar6u9L_0XJ5pDtBZZvZ7Glsj7tF09MUqkDQkZqj4pn1HsMvPVWaXtAa1zaWfPGu63HJBe_hlG7W8ZdxaQeABl7vxb3vtnm8g9pw-v2Adxx5sVyU2dj38sU0/s1600/DSC07907.JPG' },
  { id: 'geranio', name: 'Gerânio', category: 'Tristeza e acolhimento emocional', benefits: 'Equilibra instabilidades emocionais.', notes: 'Floral, Verde', intensity: 80, tags: ['Equilíbrio', 'Feminilidade'], imageUrl: 'https://www.floresefolhagens.com.br/wp-content/uploads/2015/05/geranio-pelargonium-domesticum.jpg' },
  { id: 'jasmim', name: 'Jasmim', category: 'Tristeza e acolhimento emocional', benefits: 'Preenche sensações de vazio.', notes: 'Floral Exótico', intensity: 95, tags: ['Beleza', 'Êxtase'], imageUrl: 'https://images.unsplash.com/photo-1591147139827-840360ecb791?auto=format&fit=crop&w=800' },
  { id: 'ylangylang', name: 'Ylang-Ylang', category: 'Tristeza e acolhimento emocional', benefits: 'Alivia carência afetiva.', notes: 'Doce, Floral', intensity: 90, tags: ['Paixão', 'Autoestima'], imageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800' },
  { id: 'palmarosa', name: 'Palmarosa', category: 'Tristeza e acolhimento emocional', benefits: 'Traz necessidade de conforto.', notes: 'Doce, Rosáceo', intensity: 60, tags: ['Carinho', 'Leveza'], imageUrl: 'https://images.unsplash.com/photo-1600742116039-44d5d9c28704?auto=format&fit=crop&w=800' },
  { id: 'mandarina', name: 'Mandarina', category: 'Tristeza e acolhimento emocional', benefits: 'Suaviza a melancolia.', notes: 'Cítrico Doce', intensity: 65, tags: ['Infância', 'Sorriso'], imageUrl: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?auto=format&fit=crop&w=800' },
  { id: 'laranja', name: 'Laranja-doce', category: 'Tristeza e acolhimento emocional', benefits: 'Eleva humor baixo.', notes: 'Cítrico, Fresco', intensity: 70, tags: ['Otimismo', 'Luz'], imageUrl: 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=800' },

  // Energia e motivação
  { id: 'alecrim', name: 'Alecrim', category: 'Energia e motivação', benefits: 'Combate a fadiga mental.', notes: 'Herbáceo, Fresco', intensity: 80, tags: ['Ação', 'Vigor'], imageUrl: 'https://images.unsplash.com/photo-1594315611415-090c4226379c?auto=format&fit=crop&w=800' },
  { id: 'hortela_pimenta', name: 'Hortelã-pimenta', category: 'Energia e motivação', benefits: 'Alivia cansaço e lentidão.', notes: 'Mentolado', intensity: 85, tags: ['Alerta', 'Frescor'], imageUrl: 'https://images.unsplash.com/photo-1623910931558-86d1ee00e701?auto=format&fit=crop&w=800' },
  { id: 'limao', name: 'Limão', category: 'Energia e motivação', benefits: 'Combate falta de foco.', notes: 'Cítrico', intensity: 80, tags: ['Clareza', 'Impulso'], imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800' },
  { id: 'grapefruit', name: 'Grapefruit', category: 'Energia e motivação', benefits: 'Combate a apatia.', notes: 'Cítrico, Amargo', intensity: 75, tags: ['Autoestima', 'Energia'], imageUrl: 'https://images.unsplash.com/photo-1557618153-6178229a5654?auto=format&fit=crop&w=800' },
  { id: 'eucalipto', name: 'Eucalipto', category: 'Energia e motivação', benefits: 'Libera a mente “travada”.', notes: 'Cânforaceo', intensity: 85, tags: ['Respiro', 'Abertura'], imageUrl: 'https://images.unsplash.com/photo-1597405206132-e423e8436ba4?auto=format&fit=crop&w=800' },
  { id: 'gengibre', name: 'Gengibre', category: 'Energia e motivação', benefits: 'Traz impulso e coragem.', notes: 'Picante, Quente', intensity: 90, tags: ['Fogo', 'Determinação'], imageUrl: 'https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?auto=format&fit=crop&w=800' },
  { id: 'pinho', name: 'Pinho', category: 'Energia e motivação', benefits: 'Alivia sensação de peso mental.', notes: 'Amadeirado, Resinoso', intensity: 70, tags: ['Força', 'Resiliência'], imageUrl: 'https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?auto=format&fit=crop&w=800' },
  { id: 'manjericao', name: 'Manjericão', category: 'Energia e motivação', benefits: 'Combate exaustão intelectual.', notes: 'Herbáceo, Doce', intensity: 75, tags: ['Mente', 'Renovação'], imageUrl: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=800' },

  // Foco e clareza
  { id: 'alecrim_cineol', name: 'Alecrim qt cineol', category: 'Foco e clareza', benefits: 'Focado em concentração intensa.', notes: 'Herbáceo, Cânforaceo', intensity: 80, tags: ['Estudo', 'Memória'], imageUrl: 'https://images.unsplash.com/photo-1520412099511-ea782bd2d594?auto=format&fit=crop&w=800' },
  { id: 'peppermint', name: 'Peppermint', category: 'Foco e clareza', benefits: 'Desperta mentes dispersas.', notes: 'Mentolado Forte', intensity: 90, tags: ['Lógica', 'Clarificação'], imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800' },
  { id: 'louro', name: 'Louro', category: 'Foco e clareza', benefits: 'Traz decisão e clareza.', notes: 'Herbáceo, Doce', intensity: 75, tags: ['Vitória', 'Confiança'], imageUrl: 'https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?auto=format&fit=crop&w=800' },
  { id: 'tea_tree', name: 'Tea Tree', category: 'Foco e clareza', benefits: 'Elimina confusão mental.', notes: 'Medicinal, Forte', intensity: 85, tags: ['Limpeza', 'Purificação'], imageUrl: 'https://images.unsplash.com/photo-1610992015732-2449b0c26670?auto=format&fit=crop&w=800' },
  { id: 'lemongrass', name: 'Lemongrass', category: 'Foco e clareza', benefits: 'Promove recomeço mental.', notes: 'Cítrico, Herbáceo', intensity: 80, tags: ['Renovo', 'Início'], imageUrl: 'https://images.unsplash.com/photo-1515586616690-2e4a82290dc7?auto=format&fit=crop&w=800' },
  
  // Tristeza e acolhimento emocional (continuado)
  { id: 'laranja_doce', name: 'Laranja-doce', category: 'Tristeza e acolhimento emocional', benefits: 'Eleva o humor e traz leveza.', notes: 'Cítrico, Doce', intensity: 75, tags: ['Alegria', 'Otimismo'], imageUrl: 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=800' },
  
  // Energia e motivação (continuado)
  { id: 'hortela_pimenta_energia', name: 'Hortelã-pimenta', category: 'Energia e motivação', benefits: 'Combate cansaço e lentidão.', notes: 'Mentolado', intensity: 90, tags: ['Energia', 'Alerta'], imageUrl: 'https://images.unsplash.com/photo-1623910931558-86d1ee00e701?auto=format&fit=crop&w=800' },
  
  // Confiança e autoestima
  { id: 'patchouli', name: 'Patchouli', category: 'Confiança e autoestima', benefits: 'Auxilia em momentos de insegurança.', notes: 'Terroso, Intenso', intensity: 90, tags: ['Pé no chão', 'Presença'], imageUrl: 'https://images.unsplash.com/photo-1627068053428-f9b237ec997a?auto=format&fit=crop&w=800' },
  { id: 'vetiver', name: 'Vetiver', category: 'Confiança e autoestima', benefits: 'Traz estabilidade interna.', notes: 'Amadeirado, Úmido', intensity: 85, tags: ['Raiz', 'Foco'], imageUrl: 'https://images.unsplash.com/photo-1623150502742-6a849aa94be4?auto=format&fit=crop&w=800' },
  { id: 'mirra', name: 'Mirra', category: 'Confiança e autoestima', benefits: 'Busca de força interior.', notes: 'Resinoso', intensity: 80, tags: ['Força', 'Resiliência'], imageUrl: 'https://images.unsplash.com/photo-1634027732958-3965debc308a?auto=format&fit=crop&w=800' },

  // Irritação e TPM
  { id: 'clary_sage', name: 'Clary Sage (Sálvia-esclareia)', category: 'Irritação e TPM', benefits: 'Alivia TPM e tensão hormonal.', notes: 'Herbáceo, Quente', intensity: 70, tags: ['Equilíbrio', 'Hormonal'], imageUrl: 'https://images.unsplash.com/photo-1632766324357-e1709425be32?auto=format&fit=crop&w=800' },
  { id: 'camomila_romana', name: 'Camomila romana', category: 'Irritação e TPM', benefits: 'Auxilia com raiva contida.', notes: 'Doce, Maçã', intensity: 60, tags: ['Paciência', 'Calma'], imageUrl: 'https://images.unsplash.com/photo-1544473244-f6895a69ad41?auto=format&fit=crop&w=800' },

  // Emoções profundas
  { id: 'baunilha', name: 'Baunilha', category: 'Emoções profundas', benefits: 'Necessidade de acolhimento e doçura.', notes: 'Doce, Quente', intensity: 85, tags: ['Acolhimento', 'Conforto'], imageUrl: 'https://images.unsplash.com/photo-1509339015530-0570b55502a5?auto=format&fit=crop&w=800' },
  { id: 'canela', name: 'Canela', category: 'Emoções profundas', benefits: 'Combate falta de entusiasmo pela vida.', notes: 'Especiado', intensity: 95, tags: ['Vibração', 'Entusiasmo'], imageUrl: 'https://images.unsplash.com/photo-1549491754-8ca93dc4baec?auto=format&fit=crop&w=800' }
];
